### ISSUE TITLE
Wrong font-file making bolded text turn italic

### ISSUE THREAD

**Issue by michiexile** [getpelican-themes/pelican-sober#1]
When bolding text in this theme, the result comes out italicized instead.

The Semibold block in `static/css/fonts.css` contains the code block

```css
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 600;
  src: local('Source Sans Pro Semibold'), local('SourceSansPro-Semibold'), url(../fonts/Source-Sans-Pro-Light-Italic.woff) format('woff');
}
```

The tag `url(../fonts/Source-Sans-Pro-Light-Italic.woff)` should read `url(../fonts/Source-Sans-Pro-Semibold.woff)` to render bold face properly.
